spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz!QAZ

logging:
  file:
    path: /Users/edz/Desktop/banyuan/git/JavaEE/SpringBoot/springboot/target
  level:
    root: info

