spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz!QAZ

logging:
  file:
    path: /Users/edz/Desktop/banyuan/git/JavaEE/SpringBoot/springboot/target
  level:
    root: info
mybatis:
  type-aliases-package: club.banyuan.springboot.entity
  mapper-locations: classpath*:/resources/**/*xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

#pagehelper:
#  dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

